camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks

spring:    
  mail:
    host: smtp.gmail.com
    port: 587
    username: <insert username>
    password: <insert password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true